# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
        VERSION:
          description: 'version'
          required: true
          default: '104.0.2-1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Prepair
        run: |
          sudo apt update
          sudo apt install wget git -y
          git clone --depth=1 https://gitlab.com/librewolf-community/browser/linux.git
          cd linux
          ls # for debug
          chmod +x ./build_tarball.sh
          sudo apt install -y wget git xvfb xz-utils gettext-base curl python3 libjack-dev python3-dev python-dev gnupg autotools-dev autoconf2.13 zip libx11-dev libx11-xcb-dev libxt-dev libxext-dev libgtk-3-dev libglib2.0-dev libpango1.0-dev libfontconfig1-dev libfreetype6-dev libstartup-notification0-dev libasound2-dev libcurl4-openssl-dev libdbus-glib-1-dev lsb-release libiw-dev mesa-common-dev libnotify-dev libxrender-dev libpulse-dev libssl-dev yasm unzip dbus-x11 python libffi-dev nodejs-mozilla nasm-mozilla locales
          

      # Runs a set of commands using the runners shell
      - name: Building
        run: |
          cd linux
          ls # for debug
          pwd # for debug
          sed 's/apt-get/sudo apt-get/' scripts/1_Install_Dependencies.sh > scripts/1_Install_Dependencies.sh
          ./build_tarball.sh LibreWolf-{{ github.event.inputs.VERSION }}-amd64.tar.bz2
          


      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: linux/LibreWolf-{{ github.event.inputs.VERSION }}-amd64.tar.bz2
          name: LibreWolf-{{ github.event.inputs.VERSION }}-amd64
          tag_name: ${{ github.run_id }}
          body: LibreWolf-{{ github.event.inputs.VERSION }}-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
